version: '3'

services:
  backend:
    build:
      context: ../
      dockerfile: ./src/Dockerfile
    command: >
      sh -c "chmod +x /usr/src/app/tests/docker-entrypoint.sh && /usr/src/app/tests/docker-entrypoint.sh"
    volumes:
      - ..:/usr/src/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - neo4j
    links:
      - neo4j
    environment:
      - NEO4J_BOLT_URL=bolt://neo4j:foobarbaz@neo4j:7687
      - DJANGO_SETTINGS_MODULE=settings
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_USERNAME

  neo4j:
    image: neo4j:5.4-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    expose:
      - 7474
      - 7687
    volumes:
      - db:/data/dbms
    environment:
      - NEO4J_AUTH=neo4j/foobarbaz
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - dbms.connector.bolt.listen_address=:7687
      - dbms.connector.bolt.advertised_address=:7687

volumes:
  db:
