name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8.6"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.python/caches
          key: dependencies-${{ hashFiles('requirements.txt') }}


      - name: Check for changes in requirements.txt
        id: check_requirements
        run: |
          if git diff --quiet HEAD requirements.txt; then
            echo "name=cache_hit::true" >> $GITHUB_OUTPUT
          else
            echo "name=cache_hit::false" >> $GITHUB_OUTPUT

          fi
        continue-on-error: true

      - name: Install dependencies
        if: steps.check_requirements.outputs.cache_hit == 'true'
        run: |
            pip install -r requirements.txt

      - name: Sphinx build
        run: |
            sphinx-build docs docs/_build
          
      - name: Deploy Sphinx
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true

        

