name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8.6"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          if git diff --quiet HEAD^ requirements.txt; then
            echo "Requirements file has not changed. Skipping installation."
          else
            pip install -r requirements.txt
          fi
      - name: Sphinx build
          run: |
          sphinx-build docs docs/_build
      - name: Deploy Sphinx
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true

        

